paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos satisfactoriamente de la bbdd
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor
    post:
      summary: Crea un nuevo usuario (solo para usuarios autenticados como Admin)
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/createProduct'
      

/api/products/{pid}:
    get:
      summary: Obtiene un producto a partir del id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Id del product que debe solicitarse
        schema:
          $type: String
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'

    put:
      summary: Actualiza un producto a partir del id (solo funciona con usuarios autenticados como Admin )
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Id del producto que se desea actualizar
        schema:
          $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
              
    delete:
      summary: Elimina un producto a partir del ID (solo funciona con usuarios autenticados como Admin )
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID del producto que se desea eliminar
        schema:
          type: string
    responses:
      "200":
        description: Usuario eliminado exitosamente
      "500":
        description: Error interno del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id de mongo
        nombre:
          type: String
          description: Nombre del producto
        descripcion:
          type: String
          description: Descripcion del producto
        category:
          type: String
          description: Categoria del producto
        precio:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Stock del producto
      example:
        _id: ObjectId("741dsadas321")
        nombre: nombreProducto
        descripcion: descripcionProducto
        category: categoriaProducto
        precio: 500
        stock: 10    
  requestBodies:
    updateProduct:
      type: object
      properties:
        nombre: 
          type: String
          description: Nombre
        descripcion: 
          type: String
          description: Descripcion
        category: 
          type: String
          description: Categoria
        precio: 
          type: Number
          description: Precio
        stock: 
          type: Number
          description: Stock
      example:
        nombre: nombreProducto
        descripcion: descripcionProducto
        category: categoriaProducto
        precio: 500
        stock: 10
    createProduct:
      type: object
      properties:
        nombre: 
          type: String
          description: Nombre
        descripcion: 
          type: String
          description: Descripcion
        category: 
          type: String
          description: Categoria
        precio: 
          type: Number
          description: Precio
        stock: 
          type: Number
          description: Stock
      example:
        nombre: nombreProducto
        descripcion: descripcionProducto
        category: categoriaProducto
        precio: 500
        stock: 10




